server:
  port: 8060
spring:
  application:
    name: sentinel-alibaba
  cloud:
    sentinel:
      transport:
        # 配置dashboard地址
        dashboard: 192.168.149.130:8858
      web-context-unify: false
      # dataSource是一个Map集合,可以回顾一下yml中如何编写Map集合
      datasource:
        # key:可以随意指定
        flow-rule:
          # 设置使用nacos配置中心,
          nacos:
            # 设置nacos的远程地址
            server-addr: 192.168.149.130:8848
            username: nacos
            password: nacos
            # 设置data-id 要和远程配置中心对应上
            data-id: order-sentinel-flow-rule
            # 设置使用的远程配置中心的配置文件类型为yml(图片中的是text)
            data-type: yml
            # 设置流控规则类型,也要和配置中心的规则对应
            rule-type: flow
          # zk: 设置使用zookpeer配置中心
          # consul: 设置使用consul配置中心


