server:
  port: 8089
spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.230.225:8848
        username: nacos
        password: nacos
        namespace: public

feign:
  sentinel:
    # 开启feign整合sentinel
    enabled: true