server:
  port: 8081
spring:
  application:
    name: order-openfeign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.230.128:8870
        username: nacos
        password: nacos
        namespace: public
logging:
  level:
    io.github.cnsukidayo.cloud.order.feign: debug
feign:
  client:
    config:
      service-stock:
        logger-level: full
        # 连接超时时间
        connect-timeout: 5000
        # 处理超时时间
        read-timeout: 3000
        request-interceptors:
          - io.github.cnsukidayo.cloud.order.config.FeignAuthRequestInterceptor